baseURL = 'https://enterprise-contract.dev/'
languageCode = 'en-us'
title = 'Enterprise Contract'
theme = 'github.com/basil/antora-default-ui-hugo-theme'
publishDir = '../public'
copyright = "Red Hat, Inc. All rights reserved."
relativeURLs = true
staticDir = ["../common/static", "antora"]

[params]
  since = 2023

[markup]
  [markup.asciidocext]
    [markup.asciidocext.attributes]
      "icons" = "font"
      "source-highlighter" = "highlightjs"
  [markup.highlight]
    # Disable Goldmark Chroma syntax highlighter
    codeFences = false

[menu]
  #
  # See also antora/supplemental-ui/partials/header-content.hbs
  # The links there should be kept in sync with these links.
  # TODO: DRY it up and generate the menus from a single source.
  #
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menu.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 11

  [[menu.main]]
    name = 'Documentation'
    weight = 12

  [[menu.main]]
    parent = 'Documentation'
    name = 'Overview'
    url = '/docs/ec/main'
    weight = 10

  [[menu.main]]
    parent = 'Documentation'
    name = 'CLI Reference'
    url = '/docs/ec-cli/main/ec_validate_image.html'
    weight = 20

  [[menu.main]]
    parent = 'Documentation'
    name = 'Tekton Tasks'
    url = '/docs/ec-cli/main/verify-enterprise-contract.html'
    weight = 30

  [[menu.main]]
    parent = 'Documentation'
    name = 'Configuration'
    url = '/docs/ecc/main'
    weight = 40

  [[menu.main]]
    parent = 'Documentation'
    name = 'Policies'
    url = '/docs/ec-policies/release_policy.html'
    weight = 60

  [[menu.main]]
    parent = 'Documentation'
    name = 'User Guide'
    url = '/docs/user-guide/main'
    weight = 70

  [[menu.main]]
    name = 'Source Code'
    url = 'https://github.com/enterprise-contract'
    weight = 13
    graphic = """<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
</svg>"""


[module]
[[module.imports]]
  path = 'github.com/basil/antora-default-ui-hugo-theme'
